# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=b'test', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=None, upload_to=b'./my_app/static/upload'),
        ),
        migrations.AddField(
            model_name='post',
            name='no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
