# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20171025_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=b'test', max_length=200),
        ),
    ]
